name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler:
          - { name: clang++, version: 17 }
          - { name: g++, version: 13 }

    steps:
      - uses: actions/checkout@v4

      - name: Install Clang ${{ matrix.compiler.version }}
        if: ${{ matrix.compiler.name == 'clang++' }}
        run: | 
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh ${{ matrix.compiler.version }}

      - name: Install Ninja
        run: sudo apt install ninja-build

      - name: Configure
        run: cmake -S . -B build -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=${{ matrix.compiler.name }}-${{ matrix.compiler.version }}

      - name: Build
        run: cmake --build build
