name: CI

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodule: true

      - run: ./vcpkg/bootstrap-vcpkg.sh

      - run: cmake --preset clang-release
      - run: cmake --build build
      - run: ctest --test-dir
