name: CI

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/foonathan/gcc:13

    steps:
      - uses: actions/checkout@v4
      - run: cmake --preset gcc-release
      - run: cmake --build build
      - run: ctest --test-dir build
