name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # - name: Install Clang 17
      #   run: | 
      #     wget https://apt.llvm.org/llvm.sh
      #     chmod +x llvm.sh
      #     sudo ./llvm.sh 17

      - name: Install gcc 13
        run: sudo apt install gcc-13 g++-13

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++-13

      - name: Build
        run: cmake --build build
